version: '3.8'

services:
  server:
    build:
      context: ./backend
    restart: always
    volumes:
      - ./backend/src/app/uploads:/app/uploads
      - ./backend/src/app:/app
    networks:
      - app-network
    ports:
      - "5000:5000"

  bot:
    build:
      context: ./telegrambot
    restart: always
    volumes:
      - ./backend/src/app/uploads:/telegrambot/uploads
    networks:
      - app-network
    depends_on:
      - server
    environment:
      SERVER_URL: http://server:5000

  cleanup:
    build:
      context: ./cleanup
    restart: always
    volumes:
      - ./backend/src/app/uploads:/cleanup/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge